apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: conservative-lizard-java-springboot 
  janus-idp.io/tekton: conservative-lizard-java-springboot
  backstage.io/kubernetes-id: conservative-lizard-java-springboot
  backstage.io/kubernetes-namespace: rhtap-demo 
  app.kubernetes.io/part-of: conservative-lizard-java-springboot
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  